#!/bin/sh

make clean
rm -f spdyn/Makefile
rm -f spdyn/Makefile.in
rm -f lib/Makefile
rm -f lib/Makefile.in
rm -f INSTALL
rm -f COPYING
rm -f Makefile
rm -f Makefile.in
rm -f aclocal.m4
rm -f config.h
rm -f config.h.in
rm -f config.log
rm -f config.status
rm -f configure
rm -f install-sh
rm -f missing
rm -f stamp-h1
rm -rf autom4te.cache
find . -name "*~" | xargs rm -f
